application:
  subdomain: anchor
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://anchor:3000/

services:
  anchor:
    # ghcr.io/zhfahim/anchor:0.3.1
    image: registry.lazycat.cloud/czyt/zhfahim/anchor:c9f956e5dafc81f7
    binds:
      - /lzcapp/var/data:/data
    cpu_shares: 512
    mem_limit: 512M
