application:
  subdomain: anchor
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://anchor:3000/
services:
  anchor:
    # ghcr.io/zhfahim/anchor:0.3.1
    # upstream: ghcr.io/zhfahim/anchor:0.17.1
    image: registry.lazycat.cloud/czyt/zhfahim/anchor:64810e6ce555fc00
    binds:
      - /lzcapp/var/data:/data
    cpu_shares: 512
    mem_limit: 512M
