package: community.lazycat.app.anchor
version: 0.3.1
name: Anchor
description: "Offline first, self hostable note taking application"
license: AGPL-3.0
homepage: https://github.com/ZhFahim/anchor
author: zhfahim
min_os_version: 1.5.0

locales:
  en:
    name: "Anchor"
    description: "Offline first, self hostable note taking application"
  zh:
    name: "Anchor"
    description: "离线优先的自托管笔记应用"
